### ISSUE TITLE
GitHub Updater Lite is having issues with it's plugins_api filter

### ISSUE THREAD

**Issue by ecotechie** [blogtutor/blog-tutor-support#234]
Seems we may want to add defaults to required fields $action and $args. Likely a plugin is breaking with convention...

![image](https://user-images.githubusercontent.com/11607383/220766207-c1c2779c-02ad-432e-bc91-22d653b4bffe.png)

https://github.com/blogtutor/blog-tutor-support/blob/90c5461c031c50a95042804370d666b910bec9be/github-updater.php#L96

**Comment by ecotechie** [comment]
https://developer.wordpress.org/reference/hooks/plugins_api/

**Comment by ecotechie** [comment]
This should do it...
`function plugins_api( $default = false, $action = '', $args = new stdClass() ) {`

**Comment by blogtutor** [comment]
I just saw this on 2.0-beta4 on PHP 8.2. It was displayed once on the homepage before I logged in, and it hasn't shown up since.

`Deprecated: Optional parameter $default declared before required parameter $args is implicitly treated as a required parameter in /home/968210.cloudwaysapps.com/cqnzbbyvbw/public_html/wp-content/plugins/blog-tutor-support/github-updater.php on line 96`

**Comment by blogtutor** [comment]
Fixed in 2.1
