### ISSUE TITLE
Improve handling and notification for failed Sucuri API whitelist requests

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#84]
If the Sucuri API does not respond with a "success" message after the automatic whitelisting, we should stop trying...and send an error or log message to us so we can investigate.

Perhaps it could work like this:

1. Increase the timeout limit to 20-30 seconds.
2. On each auto-whitelist attempt for a given IP address, increment a counter in the database. (Or maybe use a transient?)
3. When a "success" response comes back, reset/clear the counter.
4. If the counter hits 3 (or 4?), we should stop attempting to whitelist that address.
5. Also if the counter hits 3 or 4, we should trigger a notification to us with info. (Zapier webhook?)
6. Every 12 hours, when we clear the local IP cache, we can also clear the counter -- so it'll try again.

Thoughts?

**Comment by AndreyK92** [comment]
OK, from what I see it's a good plan.
It's hard to think of any better solutions without introducing another layer in between the client and Sucuri connections. We have two ways of making the request to Sucuri

1) **Using an ajax call to the php method** - what we're doing right now. In this case we're facing the current issue which is hard to mitigate with a different `php.ini` setup since we run in many different server environments.

2) **Using JavaScript's APIs like `XMLHttpRequest`, `fetch` etc *** - not possible for now, since Sucuri is not returning any CORS headers.

@blogtutor Please let me know if I'm missing anything...

**Comment by blogtutor** [comment]
Summary of our Zoom chat:

- Let's proceed with the "Counter" method.
- Store whitelist attempts as an array in a separate database option ("nerdpress_whitelist_attempts").
- Option will be set up with IP address as "key" and number of attempts as the "value".
- When we attempt to whitelist an IP address, add the IP address to the new option, and increment the counter.
- If value reaches 3, don't make any more whitelist attempts.
- If value reaches 3, send a Zapier webhook with info to notify us.
- Clear this new option at the same time we clear the local IP cache link (add to existing cron job).
- Change timeout limit to 15 seconds.

Alternate Option for DB storage: Change the current database "local cache" option to store the IPs in an array, with the corresponding whitelist attempt counter. 🚿🤔

**Comment by blogtutor** [comment]
Closed with 0.6.5 release!
